[package]
name = "day_11"
version = "0.1.0"
authors = ["Dave Farnham <dave.farnham@icloud.com>"]
categories = ["command-line-utilities"]
description = "Dumbo Octopus: https://adventofcode.com/2021/day/11"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
general = { path = "../../general" }
counter = "0.5.7"
ndarray = "0.15.6"
