[package]
name = "day_11"
version = "0.1.0"
authors = ["Dave Farnham <dave.farnham@icloud.com>"]
categories = ["command-line-utilities"]
description = "Cosmic Expansion: https://adventofcode.com/2023/day/11"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
general = { workspace = true }
itertools = { workspace = true }
ndarray = { workspace = true }
