[package]
name = "day_24"
version = "0.1.0"
authors = ["Dave Farnham <dave.farnham@icloud.com>"]
categories = ["command-line-utilities"]
description = "Never Tell Me The Odds: https://adventofcode.com/2023/day/24"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
general = { workspace = true }
itertools = { workspace = true }
mathru = "0.15"
num-bigint = "0.4"
#z3 = {version="0.12", features = ["static-link-z3"]}
