[package]
name = "day_14"
version = "0.1.0"
authors = ["Dave Farnham <dave.farnham@icloud.com>"]
categories = ["command-line-utilities"]
description = "Extended Polymerization: https://adventofcode.com/2021/day/14"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
counter = { workspace = true }
general = { workspace = true }
